# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
  #IN20191209
    delivery_addresses: ['irmine.rodrigues@gmail.com']
